--
-- PostgreSQL database dump
--

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games_history; Type: TABLE; Schema: public; Owner: RDev
--

CREATE TABLE public.games_history (
    id integer NOT NULL,
    room_code text NOT NULL,
    num_players integer NOT NULL,
    rounds jsonb NOT NULL,
    player_results jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    closed_at timestamp without time zone DEFAULT now(),
    player_ids jsonb DEFAULT '[]'::jsonb
);


ALTER TABLE public.games_history OWNER TO "RDev";

--
-- Name: games_history_id_seq; Type: SEQUENCE; Schema: public; Owner: RDev
--

CREATE SEQUENCE public.games_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.games_history_id_seq OWNER TO "RDev";

--
-- Name: games_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: RDev
--

ALTER SEQUENCE public.games_history_id_seq OWNED BY public.games_history.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: RDev
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username text NOT NULL,
    signal_strength integer DEFAULT 50,
    created_at timestamp without time zone DEFAULT now(),
    last_seen timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_temporary boolean DEFAULT true,
    CONSTRAINT users_signal_strength_check CHECK (((signal_strength >= 0) AND (signal_strength <= 100)))
);


ALTER TABLE public.users OWNER TO "RDev";

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: RDev
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO "RDev";

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: RDev
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: games_history id; Type: DEFAULT; Schema: public; Owner: RDev
--

ALTER TABLE ONLY public.games_history ALTER COLUMN id SET DEFAULT nextval('public.games_history_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: RDev
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: games_history; Type: TABLE DATA; Schema: public; Owner: RDev
--

COPY public.games_history (id, room_code, num_players, rounds, player_results, created_at, closed_at, player_ids) FROM stdin;
1	17J	4	[{"step": 0, "score": 0, "player": "Original", "signal": 100, "message": "ninja taco", "isOriginal": true}, {"step": 1, "score": -3, "player": "Bob", "signal": 64, "message": "finja tico", "isOriginal": false}, {"step": 2, "score": 1, "player": "Charlie", "signal": 72, "message": "ninja tacy", "isOriginal": false}, {"step": 3, "score": 1, "player": "You", "signal": 71, "message": "ninja tacu", "isOriginal": false}]	[{"username": "Charlie", "placement": 1, "final_signal": 72}, {"username": "Ayop", "placement": 2, "final_signal": 71}, {"username": "Alice", "placement": 3, "final_signal": 71}, {"username": "Bob", "placement": 4, "final_signal": 64}]	2026-02-25 13:45:59.842349	2026-02-25 13:45:59.842349	[]
2	88A	4	[{"step": 0, "score": 0, "player": "Original", "signal": 100, "message": "ninja taco", "isOriginal": true}, {"step": 1, "score": 10, "player": "Bob", "signal": 77, "message": "ninja taco", "isOriginal": false}, {"step": 2, "score": 10, "player": "Charlie", "signal": 81, "message": "ninja taco", "isOriginal": false}, {"step": 3, "score": 10, "player": "You", "signal": 80, "message": "ninja taco", "isOriginal": false}]	[{"username": "Charlie", "placement": 1, "final_signal": 81}, {"username": "Ayop", "placement": 2, "final_signal": 80}, {"username": "Bob", "placement": 3, "final_signal": 77}, {"username": "Alice", "placement": 4, "final_signal": 67}]	2026-02-25 13:53:14.248103	2026-02-25 13:53:14.248103	[]
3	79W	4	[{"step": 0, "score": 0, "player": "Original", "signal": 100, "message": "ninja taco", "isOriginal": true}, {"step": 1, "score": 1, "player": "Bob", "signal": 81, "message": "ninjq taco", "isOriginal": false}, {"step": 2, "score": 10, "player": "Charlie", "signal": 81, "message": "ninja taco", "isOriginal": false}, {"step": 3, "score": 1, "player": "You", "signal": 71, "message": "ninja tako", "isOriginal": false}]	[{"username": "Bob", "placement": 1, "final_signal": 81}, {"username": "Charlie", "placement": 2, "final_signal": 81}, {"username": "Kabum", "placement": 3, "final_signal": 71}, {"username": "Alice", "placement": 4, "final_signal": 71}]	2026-02-25 13:54:42.208711	2026-02-25 13:54:42.208711	[]
4	47D	4	[{"step": 0, "score": 0, "player": "Original", "signal": 100, "message": "ninja taco", "isOriginal": true}, {"step": 1, "score": 10, "player": "Bob", "signal": 90, "message": "ninja taco", "isOriginal": false}, {"step": 2, "score": 10, "player": "Charlie", "signal": 90, "message": "ninja taco", "isOriginal": false}, {"step": 3, "score": 10, "player": "You", "signal": 80, "message": "ninja taco", "isOriginal": false}]	[{"username": "Bob", "placement": 1, "final_signal": 90}, {"username": "Charlie", "placement": 2, "final_signal": 90}, {"username": "Ayop", "placement": 3, "final_signal": 80}, {"username": "Alice", "placement": 4, "final_signal": 71}]	2026-02-25 14:00:23.570213	2026-02-25 14:00:23.570213	[]
5	64O	4	[{"step": 0, "score": 0, "player": "Bob", "signal": 100, "message": "ninja taco penguin", "isOriginal": true}, {"step": 1, "score": 1, "player": "Charlie", "signal": 78, "message": "ninja taco pmnguin", "isOriginal": false}, {"step": 2, "score": 10, "player": "You", "signal": 90, "message": "ninja taco penguin", "isOriginal": false}, {"step": 3, "score": 1, "player": "Alice", "signal": 72, "message": "ninja taco penguih", "isOriginal": false}]	[{"username": "Yau", "placement": 1, "final_signal": 90}, {"username": "Bob", "placement": 2, "final_signal": 81}, {"username": "Charlie", "placement": 3, "final_signal": 78}, {"username": "Alice", "placement": 4, "final_signal": 72}]	2026-02-25 14:11:01.824508	2026-02-25 14:11:01.824508	[]
6	77A	4	[{"step": 0, "score": 0, "player": "Charlie", "signal": 100, "message": "ninja taco penguin", "isOriginal": true}, {"step": 1, "score": 10, "player": "You", "signal": 100, "message": "ninja taco penguin", "isOriginal": false}, {"step": 2, "score": 1, "player": "Alice", "signal": 82, "message": "ninja taco pemguin", "isOriginal": false}, {"step": 3, "score": -3, "player": "Bob", "signal": 69, "message": "ninja daco pewguin", "isOriginal": false}]	[{"username": "Kabum", "placement": 1, "final_signal": 100}, {"username": "Charlie", "placement": 2, "final_signal": 100}, {"username": "Alice", "placement": 3, "final_signal": 82}, {"username": "Bob", "placement": 4, "final_signal": 69}]	2026-02-25 14:59:59.36835	2026-02-25 14:59:59.36835	[]
7	67V	4	[{"round": 1, "messages": [{"score": 0, "player": "You", "signal": 100, "message": "mermaid pirate", "isOriginal": true}, {"score": 2, "player": "Alice", "signal": 32, "message": "mermaid pzhaxe", "isOriginal": false}, {"score": -5, "player": "Bob", "signal": 25, "message": "mermyid parate", "isOriginal": false}, {"score": -5, "player": "Charlie", "signal": 25, "message": "mezmaiv piratd", "isOriginal": false}]}, {"round": 2, "messages": [{"score": 0, "player": "Alice", "signal": 100, "message": "ninja taco", "isOriginal": true}, {"score": 2, "player": "Bob", "signal": 27, "message": "ninja tabo", "isOriginal": false}, {"score": -5, "player": "Charlie", "signal": 20, "message": "nbeja lacu", "isOriginal": false}, {"score": -5, "player": "You", "signal": 25, "message": "peeti laa_", "isOriginal": false}]}]	[{"username": "Alice", "placement": 1, "final_signal": 32}, {"username": "Bob", "placement": 2, "final_signal": 27}, {"username": "Ahaha1", "placement": 3, "final_signal": 25}, {"username": "Charlie", "placement": 4, "final_signal": 20}]	2026-02-26 16:41:19.986377	2026-02-26 16:41:19.986377	[]
9	12O	2	[{"chain": [{"player": "kokok", "signal": 100, "message": "robot volcano", "user_id": 2, "is_picker": true}, {"player": "koko", "signal": 20, "message": "_o___ ____a_o", "user_id": 1, "accuracy": 25, "signal_change": -10}], "final": "_o___ ____a_o", "round": 1, "original": "robot volcano"}]	[{"rank": 1, "signal": 30, "user_id": 2, "username": "kokok"}, {"rank": 2, "signal": 20, "user_id": 1, "username": "koko"}]	2026-03-02 18:37:00.164162	2026-03-02 18:37:00.164162	[]
8	12O	2	[{"chain": [{"player": "kokok", "signal": 100, "message": "robot volcano", "user_id": 2, "is_picker": true}, {"player": "koko", "signal": 20, "message": "_o___ ____a_o", "user_id": 1, "accuracy": 25, "signal_change": -10}], "final": "_o___ ____a_o", "round": 1, "original": "robot volcano"}]	[{"rank": 1, "signal": 30, "user_id": 2, "username": "kokok"}, {"rank": 2, "signal": 20, "user_id": 1, "username": "koko"}]	2026-03-02 18:37:00.164079	2026-03-02 18:37:00.164079	[]
10	24E	3	[{"chain": [{"player": "lolol", "signal": 100, "message": "robot penguin", "user_id": 3, "is_picker": true}, {"player": "kabum", "signal": 20, "message": "r____ _____in", "user_id": 2, "accuracy": 25, "signal_change": -10}, {"player": "oio", "signal": 20, "message": "r____ _______", "user_id": 1, "accuracy": 8.3, "signal_change": -10}], "final": "r____ _______", "round": 1, "original": "robot penguin"}]	[{"rank": 1, "signal": 30, "user_id": 3, "username": "lolol"}, {"rank": 2, "signal": 20, "user_id": 2, "username": "kabum"}, {"rank": 3, "signal": 20, "user_id": 1, "username": "oio"}]	2026-03-02 18:50:54.391979	2026-03-02 18:50:54.391979	[]
11	24E	3	[{"chain": [{"player": "lolol", "signal": 100, "message": "robot penguin", "user_id": 3, "is_picker": true}, {"player": "kabum", "signal": 20, "message": "r____ _____in", "user_id": 2, "accuracy": 25, "signal_change": -10}, {"player": "oio", "signal": 20, "message": "r____ _______", "user_id": 1, "accuracy": 8.3, "signal_change": -10}], "final": "r____ _______", "round": 1, "original": "robot penguin"}]	[{"rank": 1, "signal": 30, "user_id": 3, "username": "lolol"}, {"rank": 2, "signal": 20, "user_id": 2, "username": "kabum"}, {"rank": 3, "signal": 20, "user_id": 1, "username": "oio"}]	2026-03-02 18:50:54.392348	2026-03-02 18:50:54.392348	[]
12	24E	3	[{"chain": [{"player": "lolol", "signal": 100, "message": "robot penguin", "user_id": 3, "is_picker": true}, {"player": "kabum", "signal": 20, "message": "r____ _____in", "user_id": 2, "accuracy": 25, "signal_change": -10}, {"player": "oio", "signal": 20, "message": "r____ _______", "user_id": 1, "accuracy": 8.3, "signal_change": -10}], "final": "r____ _______", "round": 1, "original": "robot penguin"}]	[{"rank": 1, "signal": 30, "user_id": 3, "username": "lolol"}, {"rank": 2, "signal": 20, "user_id": 2, "username": "kabum"}, {"rank": 3, "signal": 20, "user_id": 1, "username": "oio"}]	2026-03-02 18:50:54.393402	2026-03-02 18:50:54.393402	[]
13	23Z	1	[{"chain": [{"player": "oio", "signal": 100, "message": "wizard rocket", "user_id": 1, "is_picker": true}, {"player": "lolo", "signal": 35, "message": "wizard rocket", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "wizard rocket", "round": 1, "original": "wizard rocket"}, {"chain": [{"player": "lolo", "signal": 100, "message": "banana spaceship", "user_id": 2, "is_picker": true}, {"player": "lolo", "signal": 40, "message": "banana spaceship", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "banana spaceship", "round": 2, "original": "banana spaceship"}]	[{"rank": 1, "signal": 30, "user_id": 2, "username": "lolo"}]	2026-03-02 19:03:24.862617	2026-03-02 19:03:24.862617	[]
14	23Z	1	[{"chain": [{"player": "oio", "signal": 100, "message": "wizard rocket", "user_id": 1, "is_picker": true}, {"player": "lolo", "signal": 35, "message": "wizard rocket", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "wizard rocket", "round": 1, "original": "wizard rocket"}, {"chain": [{"player": "lolo", "signal": 100, "message": "banana spaceship", "user_id": 2, "is_picker": true}, {"player": "lolo", "signal": 40, "message": "banana spaceship", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "banana spaceship", "round": 2, "original": "banana spaceship"}]	[{"rank": 1, "signal": 30, "user_id": 1, "username": "oio"}]	2026-03-02 19:03:24.912725	2026-03-02 19:03:24.912725	[]
15	23Z	1	[{"chain": [{"player": "oio", "signal": 100, "message": "wizard rocket", "user_id": 1, "is_picker": true}, {"player": "lolo", "signal": 35, "message": "wizard rocket", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "wizard rocket", "round": 1, "original": "wizard rocket"}, {"chain": [{"player": "lolo", "signal": 100, "message": "banana spaceship", "user_id": 2, "is_picker": true}, {"player": "lolo", "signal": 40, "message": "banana spaceship", "user_id": 2, "accuracy": 100, "signal_change": 5}], "final": "banana spaceship", "round": 2, "original": "banana spaceship"}]	[{"rank": 1, "signal": 30, "user_id": 1, "username": "oio"}]	2026-03-02 19:03:26.614012	2026-03-02 19:03:26.614012	[]
16	19Q	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "tornado mermaid", "user_id": 1, "is_picker": true}, {"player": "ola", "signal": 35, "message": "tornado mermaid", "user_id": 2, "accuracy": 100, "signal_change": 5}, {"player": "hey", "signal": 35, "message": "tornado mermaid", "user_id": 3, "accuracy": 100, "signal_change": 5}], "final": "tornado mermaid", "round": 1, "original": "tornado mermaid"}]	[{"rank": 1, "signal": 30, "user_id": 3, "username": "hey"}]	2026-03-02 19:09:53.683283	2026-03-02 19:09:53.683283	[]
17	19Q	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "tornado mermaid", "user_id": 1, "is_picker": true}, {"player": "ola", "signal": 35, "message": "tornado mermaid", "user_id": 2, "accuracy": 100, "signal_change": 5}, {"player": "hey", "signal": 35, "message": "tornado mermaid", "user_id": 3, "accuracy": 100, "signal_change": 5}], "final": "tornado mermaid", "round": 1, "original": "tornado mermaid"}]	[{"rank": 1, "signal": 30, "user_id": 2, "username": "ola"}]	2026-03-02 19:09:55.334615	2026-03-02 19:09:55.334615	[]
18	19Q	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "tornado mermaid", "user_id": 1, "is_picker": true}, {"player": "ola", "signal": 35, "message": "tornado mermaid", "user_id": 2, "accuracy": 100, "signal_change": 5}, {"player": "hey", "signal": 35, "message": "tornado mermaid", "user_id": 3, "accuracy": 100, "signal_change": 5}], "final": "tornado mermaid", "round": 1, "original": "tornado mermaid"}]	[{"rank": 1, "signal": 30, "user_id": 1, "username": "oioi"}]	2026-03-02 19:09:55.334894	2026-03-02 19:09:55.334894	[]
19	78Y	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "waffle ninja", "user_id": 1, "is_picker": true}, {"player": "oioil", "signal": 35, "message": "waffle ninja", "user_id": 3, "accuracy": 100, "signal_change": 5}, {"player": "lolo", "signal": 35, "message": "waffly ninja", "user_id": 2, "accuracy": 90.9, "signal_change": 5}], "final": "waffly ninja", "round": 1, "original": "waffle ninja"}]	[{"rank": 1, "signal": 30, "user_id": 1, "username": "oioi"}]	2026-03-02 19:31:12.418905	2026-03-02 19:31:12.418905	[]
20	78Y	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "waffle ninja", "user_id": 1, "is_picker": true}, {"player": "oioil", "signal": 35, "message": "waffle ninja", "user_id": 3, "accuracy": 100, "signal_change": 5}, {"player": "lolo", "signal": 35, "message": "waffly ninja", "user_id": 2, "accuracy": 90.9, "signal_change": 5}], "final": "waffly ninja", "round": 1, "original": "waffle ninja"}]	[{"rank": 1, "signal": 30, "user_id": 2, "username": "lolo"}]	2026-03-02 19:31:13.757579	2026-03-02 19:31:13.757579	[]
21	78Y	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "waffle ninja", "user_id": 1, "is_picker": true}, {"player": "oioil", "signal": 35, "message": "waffle ninja", "user_id": 3, "accuracy": 100, "signal_change": 5}, {"player": "lolo", "signal": 35, "message": "waffly ninja", "user_id": 2, "accuracy": 90.9, "signal_change": 5}], "final": "waffly ninja", "round": 1, "original": "waffle ninja"}]	[{"rank": 1, "signal": 35, "user_id": 3, "username": "oioil"}]	2026-03-02 19:31:13.758239	2026-03-02 19:31:13.758239	[]
22	13B	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "disco dragon", "user_id": 18, "is_picker": true, "signal_change": 0}, {"player": "lolo", "signal": 35, "message": "disco dragon", "user_id": 19, "accuracy": 100, "is_picker": false, "signal_change": 5}, {"player": "pimp", "signal": 35, "message": "discc oragon", "user_id": 20, "accuracy": 81.8, "is_picker": false, "signal_change": 5}], "final": "discc oragon", "round": 1, "original": "disco dragon"}]	[{"rank": 1, "signal": 30, "user_id": 20, "username": "pimp"}]	2026-03-02 19:50:53.233725	2026-03-02 19:50:53.233725	[]
23	13B	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "disco dragon", "user_id": 18, "is_picker": true, "signal_change": 0}, {"player": "lolo", "signal": 35, "message": "disco dragon", "user_id": 19, "accuracy": 100, "is_picker": false, "signal_change": 5}, {"player": "pimp", "signal": 35, "message": "discc oragon", "user_id": 20, "accuracy": 81.8, "is_picker": false, "signal_change": 5}], "final": "discc oragon", "round": 1, "original": "disco dragon"}]	[{"rank": 1, "signal": 30, "user_id": 19, "username": "lolo"}]	2026-03-02 19:50:54.750629	2026-03-02 19:50:54.750629	[]
24	13B	1	[{"chain": [{"player": "oioi", "signal": 100, "message": "disco dragon", "user_id": 18, "is_picker": true, "signal_change": 0}, {"player": "lolo", "signal": 35, "message": "disco dragon", "user_id": 19, "accuracy": 100, "is_picker": false, "signal_change": 5}, {"player": "pimp", "signal": 35, "message": "discc oragon", "user_id": 20, "accuracy": 81.8, "is_picker": false, "signal_change": 5}], "final": "discc oragon", "round": 1, "original": "disco dragon"}]	[{"rank": 1, "signal": 30, "user_id": 18, "username": "oioi"}]	2026-03-02 19:50:54.750862	2026-03-02 19:50:54.750862	[]
25	11J	1	[{"chain": [{"typed": "jellyfish spaceship", "player": "lolo", "user_id": 56, "accuracy": 100, "received": "jellyfish spaceship", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "sepaceish neaoelsas", "player": "oio", "user_id": 54, "accuracy": 5.6, "received": "_____f__h _____sh__", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "spaceeshh posafds_s", "player": "oioo", "user_id": 55, "accuracy": 5.6, "received": "___a__i__ ______sa_", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "spaceeshh posafds_s", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "jellyfish spaceship", "max_words": 2}]	[{"rank": 1, "signal": 20, "user_id": 55, "username": "oioo"}]	2026-03-03 10:34:19.347595	2026-03-03 10:34:19.347595	[]
26	11J	1	[{"chain": [{"typed": "jellyfish spaceship", "player": "lolo", "user_id": 56, "accuracy": 100, "received": "jellyfish spaceship", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "sepaceish neaoelsas", "player": "oio", "user_id": 54, "accuracy": 5.6, "received": "_____f__h _____sh__", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "spaceeshh posafds_s", "player": "oioo", "user_id": 55, "accuracy": 5.6, "received": "___a__i__ ______sa_", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "spaceeshh posafds_s", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "jellyfish spaceship", "max_words": 2}]	[{"rank": 1, "signal": 20, "user_id": 54, "username": "oio", "signal_strength": 20}]	2026-03-03 10:34:23.027929	2026-03-03 10:34:23.027929	[]
27	11J	1	[{"chain": [{"typed": "jellyfish spaceship", "player": "lolo", "user_id": 56, "accuracy": 100, "received": "jellyfish spaceship", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "sepaceish neaoelsas", "player": "oio", "user_id": 54, "accuracy": 5.6, "received": "_____f__h _____sh__", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "spaceeshh posafds_s", "player": "oioo", "user_id": 55, "accuracy": 5.6, "received": "___a__i__ ______sa_", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "spaceeshh posafds_s", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "jellyfish spaceship", "max_words": 2}]	[{"rank": 1, "signal": 30, "user_id": 56, "username": "lolo"}]	2026-03-03 10:34:23.02791	2026-03-03 10:34:23.02791	[]
28	82W	1	[{"chain": [{"typed": "yeti cactus", "player": "oioi", "user_id": 59, "accuracy": 100, "received": "yeti cactus", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "yeti cactus", "player": "kabum", "user_id": 60, "accuracy": 20, "received": "_e__ __c___", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "yeti cactos", "player": "kablau", "user_id": 61, "accuracy": 20, "received": "__t_ _a____", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "yeti cactos", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti cactus", "max_words": 2}]	[{"rank": 1, "signal": 30, "user_id": 59, "username": "oioi"}]	2026-03-03 10:38:49.959414	2026-03-03 10:38:49.959414	[]
29	82W	1	[{"chain": [{"typed": "yeti cactus", "player": "oioi", "user_id": 59, "accuracy": 100, "received": "yeti cactus", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "yeti cactus", "player": "kabum", "user_id": 60, "accuracy": 20, "received": "_e__ __c___", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "yeti cactos", "player": "kablau", "user_id": 61, "accuracy": 20, "received": "__t_ _a____", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "yeti cactos", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti cactus", "max_words": 2}]	[{"rank": 1, "signal": 20, "user_id": 60, "username": "kabum"}]	2026-03-03 10:38:53.159103	2026-03-03 10:38:53.159103	[]
30	82W	1	[{"chain": [{"typed": "yeti cactus", "player": "oioi", "user_id": 59, "accuracy": 100, "received": "yeti cactus", "is_picker": true, "new_signal": 30, "signal_change": 0}, {"typed": "yeti cactus", "player": "kabum", "user_id": 60, "accuracy": 20, "received": "_e__ __c___", "is_picker": false, "new_signal": 20, "signal_change": -10}, {"typed": "yeti cactos", "player": "kablau", "user_id": 61, "accuracy": 20, "received": "__t_ _a____", "is_picker": false, "new_signal": 20, "signal_change": -10}], "final": "yeti cactos", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti cactus", "max_words": 2}]	[{"rank": 1, "signal": 20, "user_id": 61, "username": "kablau", "signal_strength": 20}]	2026-03-03 10:38:53.160314	2026-03-03 10:38:53.160314	[]
31	61I	1	[{"chain": [{"typed": "pizza pirate", "player": "oio", "signal": 50, "message": "pizza pirate", "user_id": 62, "accuracy": 100, "received": "pizza pirate", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "pizza pirate", "player": "oioo", "signal": 40, "message": "pizza pirate", "user_id": 63, "accuracy": 45.5, "received": "p_z__ p___te", "is_picker": false, "new_signal": 40, "signal_change": -10}, {"typed": "pizza pilate", "player": "oiooo", "signal": 40, "message": "pizza pilate", "user_id": 64, "accuracy": 36.4, "received": "p___a __ra_e", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "pizza pilate", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "pizza pirate", "max_words": 2}]	[{"rank": 1, "signal": 40, "user_id": 63, "username": "oioo"}]	2026-03-03 10:49:21.543005	2026-03-03 10:49:21.543005	[]
32	61I	1	[{"chain": [{"typed": "pizza pirate", "player": "oio", "signal": 50, "message": "pizza pirate", "user_id": 62, "accuracy": 100, "received": "pizza pirate", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "pizza pirate", "player": "oioo", "signal": 40, "message": "pizza pirate", "user_id": 63, "accuracy": 45.5, "received": "p_z__ p___te", "is_picker": false, "new_signal": 40, "signal_change": -10}, {"typed": "pizza pilate", "player": "oiooo", "signal": 40, "message": "pizza pilate", "user_id": 64, "accuracy": 36.4, "received": "p___a __ra_e", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "pizza pilate", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "pizza pirate", "max_words": 2}]	[{"rank": 1, "signal": 40, "user_id": 64, "username": "oiooo"}]	2026-03-03 10:49:22.963695	2026-03-03 10:49:22.963695	[]
33	61I	1	[{"chain": [{"typed": "pizza pirate", "player": "oio", "signal": 50, "message": "pizza pirate", "user_id": 62, "accuracy": 100, "received": "pizza pirate", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "pizza pirate", "player": "oioo", "signal": 40, "message": "pizza pirate", "user_id": 63, "accuracy": 45.5, "received": "p_z__ p___te", "is_picker": false, "new_signal": 40, "signal_change": -10}, {"typed": "pizza pilate", "player": "oiooo", "signal": 40, "message": "pizza pilate", "user_id": 64, "accuracy": 36.4, "received": "p___a __ra_e", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "pizza pilate", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "pizza pirate", "max_words": 2}]	[{"rank": 1, "signal": 50, "user_id": 62, "username": "oio", "signal_strength": 50}]	2026-03-03 10:49:23.01786	2026-03-03 10:49:23.01786	[]
34	59R	1	[{"chain": [{"typed": "disco iguana", "player": "oio", "signal": 50, "message": "disco iguana", "user_id": 67, "accuracy": 100, "received": "disco iguana", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "disco iguana", "player": "oioi", "signal": 55, "message": "disco iguana", "user_id": 69, "accuracy": 100, "received": "d___o __uan_", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "dusco iguana", "player": "oioo", "signal": 55, "message": "dusco iguana", "user_id": 68, "accuracy": 90.9, "received": "__s_o __u_na", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "dusco iguana", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "disco iguana", "max_words": 2}, {"chain": [{"typed": "disco gorilla", "player": "oioi", "signal": 55, "message": "disco gorilla", "user_id": 69, "accuracy": 100, "received": "disco gorilla", "is_picker": true, "new_signal": 55, "signal_change": 0}, {"typed": "lidao jsrllaa", "player": "oioo", "signal": 45, "message": "lidao jsrllaa", "user_id": 68, "accuracy": 41.7, "received": "_i_c_ g____la", "is_picker": false, "new_signal": 45, "signal_change": -10}, {"typed": "dadas jfradas", "player": "oio", "signal": 40, "message": "dadas jfradas", "user_id": 67, "accuracy": 41.7, "received": "li___ ___ll_a", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "dadas jfradas", "round": 2, "votes": {"no": 0, "yes": 0}, "original": "disco gorilla", "max_words": 2}]	[{"rank": 1, "signal": 40, "user_id": 67, "username": "oio"}]	2026-03-03 10:58:34.045369	2026-03-03 10:58:34.045369	[]
35	59R	1	[{"chain": [{"typed": "disco iguana", "player": "oio", "signal": 50, "message": "disco iguana", "user_id": 67, "accuracy": 100, "received": "disco iguana", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "disco iguana", "player": "oioi", "signal": 55, "message": "disco iguana", "user_id": 69, "accuracy": 100, "received": "d___o __uan_", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "dusco iguana", "player": "oioo", "signal": 55, "message": "dusco iguana", "user_id": 68, "accuracy": 90.9, "received": "__s_o __u_na", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "dusco iguana", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "disco iguana", "max_words": 2}, {"chain": [{"typed": "disco gorilla", "player": "oioi", "signal": 55, "message": "disco gorilla", "user_id": 69, "accuracy": 100, "received": "disco gorilla", "is_picker": true, "new_signal": 55, "signal_change": 0}, {"typed": "lidao jsrllaa", "player": "oioo", "signal": 45, "message": "lidao jsrllaa", "user_id": 68, "accuracy": 41.7, "received": "_i_c_ g____la", "is_picker": false, "new_signal": 45, "signal_change": -10}, {"typed": "dadas jfradas", "player": "oio", "signal": 40, "message": "dadas jfradas", "user_id": 67, "accuracy": 41.7, "received": "li___ ___ll_a", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "dadas jfradas", "round": 2, "votes": {"no": 0, "yes": 0}, "original": "disco gorilla", "max_words": 2}]	[{"rank": 1, "signal": 45, "user_id": 68, "username": "oioo"}]	2026-03-03 10:58:35.480085	2026-03-03 10:58:35.480085	[]
36	59R	1	[{"chain": [{"typed": "disco iguana", "player": "oio", "signal": 50, "message": "disco iguana", "user_id": 67, "accuracy": 100, "received": "disco iguana", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "disco iguana", "player": "oioi", "signal": 55, "message": "disco iguana", "user_id": 69, "accuracy": 100, "received": "d___o __uan_", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "dusco iguana", "player": "oioo", "signal": 55, "message": "dusco iguana", "user_id": 68, "accuracy": 90.9, "received": "__s_o __u_na", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "dusco iguana", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "disco iguana", "max_words": 2}, {"chain": [{"typed": "disco gorilla", "player": "oioi", "signal": 55, "message": "disco gorilla", "user_id": 69, "accuracy": 100, "received": "disco gorilla", "is_picker": true, "new_signal": 55, "signal_change": 0}, {"typed": "lidao jsrllaa", "player": "oioo", "signal": 45, "message": "lidao jsrllaa", "user_id": 68, "accuracy": 41.7, "received": "_i_c_ g____la", "is_picker": false, "new_signal": 45, "signal_change": -10}, {"typed": "dadas jfradas", "player": "oio", "signal": 40, "message": "dadas jfradas", "user_id": 67, "accuracy": 41.7, "received": "li___ ___ll_a", "is_picker": false, "new_signal": 40, "signal_change": -10}], "final": "dadas jfradas", "round": 2, "votes": {"no": 0, "yes": 0}, "original": "disco gorilla", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 69, "username": "oioi", "signal_strength": 55}]	2026-03-03 10:58:35.480298	2026-03-03 10:58:35.480298	[]
37	95U	1	[{"chain": [{"typed": "ninja dragon", "player": "oio", "signal": 50, "message": "ninja dragon", "user_id": 70, "accuracy": 100, "received": "ninja dragon", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ninja drakon", "player": "lol", "signal": 55, "message": "ninja drakon", "user_id": 71, "accuracy": 90.9, "received": "__nj_ __a_on", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "ninja dragon", "player": "pimba", "signal": 55, "message": "ninja dragon", "user_id": 72, "accuracy": 90.9, "received": "n_n__ _rak__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "ninja dragon", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja dragon", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 72, "username": "pimba"}]	2026-03-03 11:13:33.912767	2026-03-03 11:13:33.912767	[]
38	95U	1	[{"chain": [{"typed": "ninja dragon", "player": "oio", "signal": 50, "message": "ninja dragon", "user_id": 70, "accuracy": 100, "received": "ninja dragon", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ninja drakon", "player": "lol", "signal": 55, "message": "ninja drakon", "user_id": 71, "accuracy": 90.9, "received": "__nj_ __a_on", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "ninja dragon", "player": "pimba", "signal": 55, "message": "ninja dragon", "user_id": 72, "accuracy": 90.9, "received": "n_n__ _rak__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "ninja dragon", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja dragon", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 71, "username": "lol"}]	2026-03-03 11:13:35.677176	2026-03-03 11:13:35.677176	[]
39	95U	1	[{"chain": [{"typed": "ninja dragon", "player": "oio", "signal": 50, "message": "ninja dragon", "user_id": 70, "accuracy": 100, "received": "ninja dragon", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ninja drakon", "player": "lol", "signal": 55, "message": "ninja drakon", "user_id": 71, "accuracy": 90.9, "received": "__nj_ __a_on", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "ninja dragon", "player": "pimba", "signal": 55, "message": "ninja dragon", "user_id": 72, "accuracy": 90.9, "received": "n_n__ _rak__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "ninja dragon", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja dragon", "max_words": 2}]	[{"rank": 1, "signal": 50, "user_id": 70, "username": "oio", "signal_strength": 50}]	2026-03-03 11:13:35.677449	2026-03-03 11:13:35.677449	[]
40	11A	3	[{"chain": [{"typed": "cactus giraffe", "player": "abcs", "signal": 50, "message": "cactus giraffe", "user_id": 73, "accuracy": 100, "received": "cactus giraffe", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "cactus girrafe", "player": "32132", "signal": 55, "message": "cactus girrafe", "user_id": 74, "accuracy": 84.6, "received": "ca__u_ ___aff_", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "dacsas gmdnafe", "player": "dsjakdas", "signal": 51, "message": "dacsas gmdnafe", "user_id": 75, "accuracy": 53.8, "received": "c_c__s _ir___e", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "dacsas gmdnafe", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "cactus giraffe", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 74, "username": "32132"}, {"rank": 2, "signal": 51, "user_id": 75, "username": "dsjakdas"}, {"rank": 3, "signal": 50, "user_id": 73, "username": "abcs"}]	2026-03-03 13:00:07.379618	2026-03-03 13:00:07.379618	[]
41	39K	3	[{"chain": [{"typed": "hamster robot", "player": "o33", "signal": 50, "message": "hamster robot", "user_id": 78, "accuracy": 100, "received": "hamster robot", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "hamster robot", "player": "oi2", "signal": 60, "message": "hamster robot", "user_id": 76, "accuracy": 100, "received": "__ms_e_ _ob__", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "lalstll lollt", "player": "oi1", "signal": 49, "message": "lalstll lollt", "user_id": 77, "accuracy": 41.7, "received": "____ter _o_o_", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "lalstll lollt", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "hamster robot", "max_words": 2}, {"chain": [{"typed": "disco turtle dolphin", "player": "oi1", "signal": 49, "message": "disco turtle dolphin", "user_id": 77, "accuracy": 100, "received": "disco turtle dolphin", "is_picker": true, "new_signal": 49, "signal_change": 0}, {"typed": "disco turtle _ol__i_", "player": "o33", "signal": 55, "message": "disco turtle _ol__i_", "user_id": 78, "accuracy": 77.8, "received": "d__c_ __rtl_ d_l___n", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "disco turtle colliid", "player": "oi2", "signal": 65, "message": "disco turtle colliid", "user_id": 76, "accuracy": 77.8, "received": "_i_co tu__l_ __l__i_", "is_picker": false, "new_signal": 65, "signal_change": 5}], "final": "disco turtle colliid", "round": 3, "votes": {"no": 0, "yes": 0}, "original": "disco turtle dolphin", "max_words": 3}]	[{"rank": 1, "signal": 65, "user_id": 76, "username": "oi2"}, {"rank": 2, "signal": 55, "user_id": 78, "username": "o33"}, {"rank": 3, "signal": 49, "user_id": 77, "username": "oi1"}]	2026-03-03 13:16:44.005728	2026-03-03 13:16:44.005728	[]
42	36H	3	[{"chain": [{"typed": "pirate pizza", "player": "oio", "signal": 50, "message": "pirate pizza", "user_id": 79, "accuracy": 100, "received": "pirate pizza", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "pirata pizza", "player": "lolo", "signal": 55, "message": "pirata pizza", "user_id": 80, "accuracy": 90.9, "received": "pir___ __zz_", "is_picker": false, "new_signal": 55, "signal_change": 5}, {"typed": "piratt pefzg", "player": "213", "signal": 51, "message": "piratt pefzg", "user_id": 81, "accuracy": 63.6, "received": "pi___a __z_a", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "piratt pefzg", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "pirate pizza", "max_words": 2}, {"chain": [{"typed": "burrito unicorn mermaid", "player": "oio", "signal": 50, "message": "burrito unicorn mermaid", "user_id": 79, "accuracy": 100, "received": "burrito unicorn mermaid", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "burrito nniihjn seara_d", "player": "lolo", "signal": 56, "message": "burrito nniihjn seara_d", "user_id": 80, "accuracy": 61.9, "received": "b__ri__ ___co_n mer____", "is_picker": false, "new_signal": 56, "signal_change": 1}], "final": "burrito nniihjn seara_d", "round": 3, "votes": {"no": 0, "yes": 0}, "original": "burrito unicorn mermaid", "max_words": 3}]	[{"rank": 1, "signal": 56, "user_id": 80, "username": "lolo"}, {"rank": 2, "signal": 51, "user_id": 81, "username": "213"}, {"rank": 3, "signal": 50, "user_id": 79, "username": "oio"}]	2026-03-03 16:16:55.624166	2026-03-03 16:16:55.624166	[]
43	27N	3	[{"chain": [{"typed": "ninja zebra", "player": "oio", "signal": 50, "message": "ninja zebra", "user_id": 82, "accuracy": 100, "received": "ninja zebra", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ninja zebra", "player": "lpls", "signal": 60, "message": "ninja zebra", "user_id": 84, "accuracy": 100, "received": "___ja __br_", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "zinzz zzzra", "player": "kaka", "signal": 51, "message": "zinzz zzzra", "user_id": 83, "accuracy": 50, "received": "ni___ ___ra", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "zinzz zzzra", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja zebra", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 84, "username": "lpls"}, {"rank": 2, "signal": 51, "user_id": 83, "username": "kaka"}, {"rank": 3, "signal": 50, "user_id": 82, "username": "oio"}]	2026-03-03 16:28:49.395037	2026-03-03 16:28:49.395037	[]
44	90O	3	[{"chain": [{"typed": "gorilla turtle", "player": "oio", "signal": 50, "message": "gorilla turtle", "user_id": 85, "accuracy": 100, "received": "gorilla turtle", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "gorilla turtle", "player": "oio2", "signal": 60, "message": "gorilla turtle", "user_id": 86, "accuracy": 100, "received": "g__i__a tu_t__", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "gordasq turqqq", "player": "oio3", "signal": 49, "message": "gordasq turqqq", "user_id": 87, "accuracy": 46.2, "received": "g___ll_ ___tle", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "gordasq turqqq", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "gorilla turtle", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 86, "username": "oio2"}, {"rank": 2, "signal": 50, "user_id": 85, "username": "oio"}, {"rank": 3, "signal": 49, "user_id": 87, "username": "oio3"}]	2026-03-03 17:22:54.120081	2026-03-03 17:22:54.120081	[]
45	91B	3	[{"chain": [{"typed": "robot cactus", "player": "oioi", "signal": 50, "message": "robot cactus", "user_id": 88, "accuracy": 100.0, "received": "robot cactus", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "robot cactus", "player": "oioi3", "signal": 60, "message": "robot cactus", "user_id": 90, "accuracy": 100.0, "received": "__b_t __c_us", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "lllot caclll", "player": "oioi2", "signal": 49, "message": "lllot caclll", "user_id": 89, "accuracy": 45.5, "received": "_ob__ __ct_s", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "lllot caclll", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "robot cactus", "max_words": 2}]	[{"rank": 1, "signal": 50, "user_id": 88, "username": "oioi"}, {"rank": 2, "signal": 50, "user_id": 90, "username": "oioi3"}, {"rank": 3, "signal": 49, "user_id": 89, "username": "oioi2"}]	2026-03-03 18:25:02.180638	2026-03-03 18:25:02.180638	[]
46	80N	3	[{"chain": [{"typed": "ninja dragon", "player": "123", "signal": 50, "message": "ninja dragon", "user_id": 93, "accuracy": 100.0, "received": "ninja dragon", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ninja dragon", "player": "1234", "signal": 60, "message": "ninja dragon", "user_id": 92, "accuracy": 100.0, "received": "__n_a _r__on", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "nizzz zragzz", "player": "1235", "signal": 49, "message": "nizzz zragzz", "user_id": 91, "accuracy": 45.5, "received": "_in__ d_ag__", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "nizzz zragzz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja dragon", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 92, "username": "1234"}, {"rank": 2, "signal": 50, "user_id": 93, "username": "123"}, {"rank": 3, "signal": 49, "user_id": 91, "username": "1235"}]	2026-03-03 18:41:17.448031	2026-03-03 18:41:17.448031	[]
47	86D	3	[{"chain": [{"typed": "yeti cactus", "player": "gfads", "signal": 50, "message": "yeti cactus", "user_id": 99, "accuracy": 100.0, "received": "yeti cactus", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "ketk ckktks", "player": "123231", "signal": 51, "message": "ketk ckktks", "user_id": 98, "accuracy": 50.0, "received": "y_t_ _ac__s", "is_picker": false, "new_signal": 51, "signal_change": 1}, {"typed": "yetk ckctks", "player": "lksla", "signal": 55, "message": "yetk ckctks", "user_id": 97, "accuracy": 80.0, "received": "k_t_ _kk__s", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "yetk ckctks", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti cactus", "max_words": 2}, {"chain": [{"typed": "gorilla ninja", "player": "gfads", "signal": 50, "message": "gorilla ninja", "user_id": 99, "accuracy": 100.0, "received": "gorilla ninja", "is_picker": true, "new_signal": 50, "signal_change": 0}], "final": "gorilla ninja", "round": 2, "votes": {"no": 0, "yes": 0}, "original": "gorilla ninja", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 97, "username": "lksla"}, {"rank": 2, "signal": 51, "user_id": 98, "username": "123231"}, {"rank": 3, "signal": 50, "user_id": 99, "username": "gfads"}]	2026-03-03 19:10:02.133052	2026-03-03 19:10:02.133052	[]
48	90C	3	[{"chain": [{"typed": "burrito cactus", "player": "oias", "signal": 50, "message": "burrito cactus", "user_id": 100, "accuracy": 100.0, "received": "burrito cactus", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "burrito cactus", "player": "321312", "signal": 60, "message": "burrito cactus", "user_id": 101, "accuracy": 100.0, "received": "__r_it_ c__t_s", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "zzrrztz zaztuz", "player": "fgdsdas", "signal": 49, "message": "zzrrztz zaztuz", "user_id": 102, "accuracy": 46.2, "received": "bu___t_ ___tus", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "zzrrztz zaztuz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "burrito cactus", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 101, "username": "321312"}, {"rank": 2, "signal": 50, "user_id": 100, "username": "oias"}, {"rank": 3, "signal": 49, "user_id": 102, "username": "fgdsdas"}]	2026-03-05 10:21:54.607482	2026-03-05 10:21:54.607482	[]
49	90C	3	[{"chain": [{"typed": "burrito cactus", "player": "oias", "signal": 50, "message": "burrito cactus", "user_id": 100, "accuracy": 100, "received": "burrito cactus", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "burrito cactus", "player": "321312", "signal": 60, "message": "burrito cactus", "user_id": 101, "accuracy": 100, "received": "__r_it_ c__t_s", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "zzrrztz zaztuz", "player": "fgdsdas", "signal": 49, "message": "zzrrztz zaztuz", "user_id": 102, "accuracy": 46.2, "received": "bu___t_ ___tus", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "zzrrztz zaztuz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "burrito cactus", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 101, "username": "321312"}, {"rank": 2, "signal": 50, "user_id": 100, "username": "oias"}, {"rank": 3, "signal": 49, "user_id": 102, "username": "fgdsdas"}]	2026-03-05 10:21:54.627026	2026-03-05 10:21:54.627026	[]
50	79X	3	[{"chain": [{"typed": "disco taco", "player": "dsa das", "signal": 50, "message": "disco taco", "user_id": 103, "accuracy": 100.0, "received": "disco taco", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "disco taco", "player": "gfdas", "signal": 60, "message": "disco taco", "user_id": 104, "accuracy": 100.0, "received": "__s_o t_c_", "is_picker": false, "new_signal": 60, "signal_change": 10}, {"typed": "zizcz zzco", "player": "gfsa", "signal": 49, "message": "zizcz zzco", "user_id": 105, "accuracy": 44.4, "received": "_i__o t__o", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "zizcz zzco", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "disco taco", "max_words": 2}]	[{"rank": 1, "signal": 60, "user_id": 104, "username": "gfdas"}, {"rank": 2, "signal": 50, "user_id": 103, "username": "dsa das"}, {"rank": 3, "signal": 49, "user_id": 105, "username": "gfsa"}]	2026-03-05 10:37:46.619705	2026-03-05 10:37:46.619705	[103, 104, 105]
51	10Q	3	[{"chain": [{"typed": "ninja zombie", "player": "dasd", "signal": 50, "message": "ninja zombie", "user_id": 107, "accuracy": 100.0, "received": "ninja zombie", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "nicvb zomdff", "player": "gfrd", "signal": 49, "message": "nicvb zomdff", "user_id": 108, "accuracy": 45.5, "received": "n__j_ z__bi_", "is_picker": false, "new_signal": 49, "signal_change": -1}, {"typed": "diasb domsfa", "player": "asd", "signal": 49, "message": "diasb domsfa", "user_id": 106, "accuracy": 45.5, "received": "___vb _o_d_f", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "diasb domsfa", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja zombie", "max_words": 2}]	[{"rank": 1, "signal": 50, "user_id": 107, "username": "dasd"}, {"rank": 2, "signal": 49, "user_id": 108, "username": "gfrd"}, {"rank": 3, "signal": 49, "user_id": 106, "username": "asd"}]	2026-03-05 10:56:22.968548	2026-03-05 10:56:22.968548	[107, 108, 106]
52	10Q	3	[{"chain": [{"typed": "ninja zombie", "player": "dasd", "signal": 50, "message": "ninja zombie", "user_id": 107, "accuracy": 100.0, "received": "ninja zombie", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "nicvb zomdff", "player": "gfrd", "signal": 49, "message": "nicvb zomdff", "user_id": 108, "accuracy": 45.5, "received": "n__j_ z__bi_", "is_picker": false, "new_signal": 49, "signal_change": -1}, {"typed": "diasb domsfa", "player": "asd", "signal": 49, "message": "diasb domsfa", "user_id": 106, "accuracy": 45.5, "received": "___vb _o_d_f", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "diasb domsfa", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "ninja zombie", "max_words": 2}]	[{"rank": 1, "signal": 50, "user_id": 107, "username": "dasd"}, {"rank": 2, "signal": 49, "user_id": 108, "username": "gfrd"}, {"rank": 3, "signal": 49, "user_id": 106, "username": "asd"}]	2026-03-05 10:56:24.408457	2026-03-05 10:56:24.408457	[107, 108, 106]
53	49D	3	[{"chain": [{"typed": "waffle taco", "player": "iugh", "signal": 50, "message": "waffle taco", "user_id": 109, "accuracy": 100.0, "received": "waffle taco", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "zazflz zac_", "player": "21\\\\2", "signal": 51, "message": "zazflz zac_", "user_id": 110, "accuracy": 50.0, "received": "_aff__ ta__", "is_picker": false, "new_signal": 51, "signal_change": 1}, {"typed": "zazzzz z_c_", "player": "321321", "signal": 51, "message": "zazzzz z_c_", "user_id": 111, "accuracy": 60.0, "received": "_az_l_ _ac_", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "zazzzz z_c_", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "waffle taco", "max_words": 2}]	[{"rank": 1, "signal": 51, "user_id": 110, "username": "21\\\\2"}, {"rank": 2, "signal": 51, "user_id": 111, "username": "321321"}, {"rank": 3, "signal": 50, "user_id": 109, "username": "iugh"}]	2026-03-05 11:07:21.74526	2026-03-05 11:07:21.74526	[109, 110, 111]
54	49D	3	[{"chain": [{"typed": "waffle taco", "player": "iugh", "signal": 50, "message": "waffle taco", "user_id": 109, "accuracy": 100.0, "received": "waffle taco", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "zazflz zac_", "player": "21\\\\2", "signal": 51, "message": "zazflz zac_", "user_id": 110, "accuracy": 50.0, "received": "_aff__ ta__", "is_picker": false, "new_signal": 51, "signal_change": 1}, {"typed": "zazzzz z_c_", "player": "321321", "signal": 51, "message": "zazzzz z_c_", "user_id": 111, "accuracy": 60.0, "received": "_az_l_ _ac_", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "zazzzz z_c_", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "waffle taco", "max_words": 2}]	[{"rank": 1, "signal": 51, "user_id": 110, "username": "21\\\\2"}, {"rank": 2, "signal": 51, "user_id": 111, "username": "321321"}, {"rank": 3, "signal": 50, "user_id": 109, "username": "iugh"}]	2026-03-05 11:07:23.163711	2026-03-05 11:07:23.163711	[109, 110, 111]
55	81Y	3	[{"chain": [{"typed": "yeti rocket", "player": "321321", "signal": 50, "message": "yeti rocket", "user_id": 112, "accuracy": 100.0, "received": "yeti rocket", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "yezz rozzzt", "player": "321321", "signal": 51, "message": "yezz rozzzt", "user_id": 113, "accuracy": 50.0, "received": "y__i _o_ke_", "is_picker": false, "new_signal": 51, "signal_change": 1}, {"typed": "zezz rozzzz", "player": "12312312", "signal": 55, "message": "zezz rozzzz", "user_id": 114, "accuracy": 80.0, "received": "_e_z ro_z__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "zezz rozzzz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti rocket", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 114, "username": "12312312"}, {"rank": 2, "signal": 51, "user_id": 113, "username": "321321"}, {"rank": 3, "signal": 50, "user_id": 112, "username": "321321"}]	2026-03-05 11:18:51.216461	2026-03-05 11:18:51.216461	[112, 113, 114]
56	81Y	3	[{"chain": [{"typed": "yeti rocket", "player": "321321", "signal": 50, "message": "yeti rocket", "user_id": 112, "accuracy": 100.0, "received": "yeti rocket", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "yezz rozzzt", "player": "321321", "signal": 51, "message": "yezz rozzzt", "user_id": 113, "accuracy": 50.0, "received": "y__i _o_ke_", "is_picker": false, "new_signal": 51, "signal_change": 1}, {"typed": "zezz rozzzz", "player": "12312312", "signal": 55, "message": "zezz rozzzz", "user_id": 114, "accuracy": 80.0, "received": "_e_z ro_z__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "zezz rozzzz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti rocket", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 114, "username": "12312312"}, {"rank": 2, "signal": 51, "user_id": 113, "username": "321321"}, {"rank": 3, "signal": 50, "user_id": 112, "username": "321321"}]	2026-03-05 11:18:53.389286	2026-03-05 11:18:53.389286	[112, 113, 114]
57	60G	3	[{"chain": [{"typed": "raccoon werewolf", "player": "dasdas", "signal": 50, "message": "raccoon werewolf", "user_id": 115, "accuracy": 100.0, "received": "raccoon werewolf", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "zzcczzn zezezo_f", "player": "gfds", "signal": 49, "message": "zzcczzn zezezo_f", "user_id": 116, "accuracy": 46.7, "received": "__cc_o_ w___wo_f", "is_picker": false, "new_signal": 49, "signal_change": -1}, {"typed": "zzczzzn zzzezozz", "player": "dasdas", "signal": 55, "message": "zzczzzn zzzezozz", "user_id": 117, "accuracy": 73.3, "received": "z___zz_ _e__zo__", "is_picker": false, "new_signal": 55, "signal_change": 5}], "final": "zzczzzn zzzezozz", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "raccoon werewolf", "max_words": 2}]	[{"rank": 1, "signal": 55, "user_id": 117, "username": "dasdas"}, {"rank": 2, "signal": 50, "user_id": 115, "username": "dasdas"}, {"rank": 3, "signal": 49, "user_id": 116, "username": "gfds"}]	2026-03-05 11:25:25.393011	2026-03-05 11:25:25.393011	[115, 116, 117]
58	23N	3	[{"chain": [{"typed": "yeti robot", "player": "dsadas", "signal": 50, "message": "yeti robot", "user_id": 118, "accuracy": 100.0, "received": "yeti robot", "is_picker": true, "new_signal": 50, "signal_change": 0}, {"typed": "zezi zozzt", "player": "gfdsa", "signal": 49, "message": "zezi zozzt", "user_id": 119, "accuracy": 44.4, "received": "ye__ __bo_", "is_picker": false, "new_signal": 49, "signal_change": -1}, {"typed": "yeti zebza", "player": "gfda", "signal": 49, "message": "yeti zebza", "user_id": 120, "accuracy": 44.4, "received": "_ez_ ___zt", "is_picker": false, "new_signal": 49, "signal_change": -1}], "final": "yeti zebza", "round": 1, "votes": {"no": 0, "yes": 0}, "original": "yeti robot", "max_words": 2}, {"chain": [{"typed": "taco wizard", "player": "gfdsa", "signal": 49, "message": "taco wizard", "user_id": 119, "accuracy": 100.0, "received": "taco wizard", "is_picker": true, "new_signal": 49, "signal_change": 0}, {"typed": "taco wizard", "player": "gfda", "signal": 59, "message": "taco wizard", "user_id": 120, "accuracy": 100.0, "received": "t___ ___a_d", "is_picker": false, "new_signal": 59, "signal_change": 10}, {"typed": "aaao aazaad", "player": "dsadas", "signal": 51, "message": "aaao aazaad", "user_id": 118, "accuracy": 50.0, "received": "t__o __zar_", "is_picker": false, "new_signal": 51, "signal_change": 1}], "final": "aaao aazaad", "round": 2, "votes": {"no": 0, "yes": 0}, "original": "taco wizard", "max_words": 2}]	[{"rank": 1, "signal": 59, "user_id": 120, "username": "gfda"}, {"rank": 2, "signal": 51, "user_id": 118, "username": "dsadas"}, {"rank": 3, "signal": 49, "user_id": 119, "username": "gfdsa"}]	2026-03-05 11:36:56.677658	2026-03-05 11:36:56.677658	[118, 119, 120]
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: RDev
--

COPY public.users (id, username, signal_strength, created_at, last_seen, is_temporary) FROM stdin;
\.


--
-- Name: games_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: RDev
--

SELECT pg_catalog.setval('public.games_history_id_seq', 58, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: RDev
--

SELECT pg_catalog.setval('public.users_id_seq', 120, true);


--
-- Name: games_history games_history_pkey; Type: CONSTRAINT; Schema: public; Owner: RDev
--

ALTER TABLE ONLY public.games_history
    ADD CONSTRAINT games_history_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: RDev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: RDev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO "RDev";


--
-- PostgreSQL database dump complete
--

\unrestrict 5dvw0MddnmmUYk36zwm4qMQynhunylfFm8kCvftKWVsPhqfM6fUSOxgTrBbKKEv

