version: '3.8'

services:
  whisperchain:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
      - DB_HOST=aws-1-eu-west-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.ttysfjpeuhaexglepunv
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=postgres
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    restart: unless-stopped
